# Generated by Django 2.1.7 on 2019-10-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.Playlist'),
        ),
    ]
