# Generated by Django 2.1.7 on 2019-10-06 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_uploadinguser'),
        ('video', '0003_video_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
        migrations.AddField(
            model_name='video',
            name='uploading_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.UploadingUser'),
            preserve_default=False,
        ),
    ]
